### ISSUE TITLE
No need to write a const_assert RFC (at most it would be syntactic sugar)

### ISSUE THREAD

**Issue by rodrimati1992** [dtolnay/case-studies#1]
The [future section](https://github.com/dtolnay/case-studies/tree/ecd60812b2cad5d5b07a6aa1eb8a47ff47d551a1/bitfield-assertion#future) in `Multiple of 8 const assertion` talks about creating a const_assert rfc.

The already accepted rfc for assertions in constants [is this one](https://github.com/rust-lang/rfcs/blob/master/text/2345-const-panic.md),
which combined with [const_wildcard](https://github.com/rust-lang/rfcs/blob/master/text/2526-const-wildcard.md) would allow doing const assertions outside of any item.

Example of how it will look once both RFCS are fully implemented:
```
const _:()=assert!(SIZE % 8 == 0, "total size is required to be a multiple of 8 bits");
```

**Comment by dtolnay** [comment]
Thanks for bringing this up. From skimming those two RFCs, I don't get the impression that `const _: () = assert!(...)` would be a sufficient solution. I think it would hit the behavior described under [*First attempt*](https://github.com/dtolnay/case-studies/tree/09f455df236e68fde248c97d48cc2a5081245d1d/bitfield-assertion#first-attempt) of consts not being evaluated during `cargo check`.

**Comment by rodrimati1992** [comment]
Doing `cargo check` with this code:

```rust
#![feature(underscore_const_names)]
macro_rules! require_multiple_of_eight {
    ($e:expr) => {
        const _: () = [()][$e % 8];
    };
}

require_multiple_of_eight!{10}
```

Causes this error message (in both stable and nightly Rust):

```
error: any use of this value will cause an error
  --> src/lib.rs:4:23
   |
4  |           const _: () = [()][$e % 8];
   |           --------------^^^^^^^^^^^^-
   |                         |
   |                         index out of bounds: the len is 1 but the index is 2
...
8  | / require_multiple_of_eight!{
9  | |     10
10 | | }
   | |_- in this macro invocation
   |
   = note: #[deny(const_err)] on by default
```

Are you saying that it might stop producing that error at some point?

Also,`const_assert` is [one of the motivations](https://github.com/rust-lang/rfcs/blob/master/text/2526-const-wildcard.md#rationale) for the const_wildcard RFC.

**Comment by dtolnay** [comment]
Please see #6. Let's reopen if the compiler implementation goes in the right direction to make `const _` usable for this purpose.
