### ISSUE TITLE
autoref specialization vs. generic traits

### ISSUE THREAD

**Issue by llogiq** [dtolnay/case-studies#11]
I'm in the process of moving overflower to autoref specialization. I have found that it works as you described in the unary operation case (e.g. specializing `std::ops::Neg` vs. `overflower::OverflowerNeg`).

However, there is a small niggle when the trait is generic over some other type as for example `std::ops::Add<RHS = Self>` is over `RHS`. In this case, if I try to implement the kind for `T: std::ops::Add`, this only works for the default RHS type (which is `Self`, but e.g. `String` implements `Add` for various other types (e.g. `&'_ str` and `Cow<'_, str>`).

Thus we must allow our kind to be implemented for arbitrary `RHS`. So let's try that:

```
pub struct OverflowerAddTag;
pub trait OverflowerAddKind<R> {
    fn overflower_add_tag() -> OverflowerAddTag {
        OverflowerAddTag
    }
}

impl<R, T> OverflowerAddKind<R> for T where &T: std::ops::Add<R> {}
impl<R, T> OverflowerAddKind<R> for T where T: OverflowerAdd<R> {}
```

Now the compiler tells us that we need to give a lifetime to `&T`, so we do that, which gives us:

```
impl<'a, R, T: 'a> OverflowerAddKind<R> for T where &'a T: std::ops::Add<R> {}
```

This works. Just wanted to let you know.

**Comment by dtolnay** [comment]
I don't think you are doing it right—I would expect to see an impl that looks like `for &T where T: ...`.

**Comment by llogiq** [comment]
Sorry, I fixed that after copying and forgot to update it in the text. The macro code for the kind `impl`s is now (where $std_ty → $std_kind is the fallback and $ovf_ty → $ovf_kind the overflower specialization):

```
impl<'a, R, T: 'a> $std_kind<R> for &'a T where T: $std_ty<R> {}
impl<R, T> $ovf_kind<R> for T where T: $ovf_ty<R> {}
```

**Comment by dtolnay** [comment]
Looks good, but now I believe you shouldn't need the explicit named lifetime anymore, matching what's in the writeup.

```rust
impl<R, T> $std_kind<R> for &T where T: $std_ty<R> {}
```

**Comment by llogiq** [comment]
Yes, I just tried. I think I added them on request of the compiler when I had the `&` in the wrong position.

Thank you! If you want, I can send a PR your way to add a few sentences about multiple generic arguments, otherwise feel free to close this.

**Comment by llogiq** [comment]
Ah, there's another niggle: Specializing e.g. the AddAssign trait requires mutably borrowing `self`. So if I e.g. change `a += b` to `{ let x = &mut a; (&x).overflower_add_tag().add_assign_wrap(x, b); }`, the trait dispatch fails to work (because we don't have `&T`, but `&&mut T`).

**Comment by llogiq** [comment]
I did a reborrow, but that was apparently too complex for type inference, I had to add a `_: &R` argument to `overflower_add_tag(..)`. To keep the macro simple (and to ensure it doesn't fail in the presence of multiple implementations for various `R`s), I changed the binops, too.

Now `a+b` becomes `{ let (x, y) = (a, b); (&x).overflower_add_tag(&y).add_panic(x, y) }` and `a+=b` becomes `{ let (x, y) = (a, b); (&x).overflower_add_assign_tag(&y).add_assign_panic(x, y) }` (under `#[overflow(panic)]`).

**Comment by dtolnay** [comment]
The first one looks good.

The second one doesn't look right. I don't see how that ends up mutating `a`.

**Comment by llogiq** [comment]
`add_assign_panic` takes a &mut self. Since `x = &mut a` it mutates `a`.

**Comment by dtolnay** [comment]
Okay, if `x = &mut a` that's fine. You pasted `let (x, y) = (a, b);` in which `x = a`.

**Comment by llogiq** [comment]
I have one test failure: Consider the above change. `let x = &255_u8; x + x` gets changed to `{ let (x, y) = (x, x); (&x).overflower_add_tag(&y).add_wrap(x, y) }`. Problem is, this selects the `std::Add` implementation (because `x: &u8`) instead of the specialized wrapping one. Any idea how to deal with that?

**Comment by llogiq** [comment]
I think the error is that I lost the implementations of `OverflowerAdd` for `&_` in the refactoring. Unfortunately, extending the macros to get them back isn't completely trivial.

**Comment by dtolnay** [comment]
Are you missing an overflowing Add impl for &u8 + &u8?

**Comment by llogiq** [comment]
It appears so.

**Comment by llogiq** [comment]
Now that I added the forwarding impls to my overflower traits, I get a new error:

```
error[E0034]: multiple applicable items in scope
  --> overflower/tests/simple.rs:58:1
   |
58 | #[overflow(wrap)]
   | ^^^^^^^^^^^^^^^^^ multiple `overflower_add_tag` found
   |
   = note: candidate #1 is defined in an impl of the trait `overflower::OverflowerStdAddKind` for the type `&_`
   = help: to disambiguate the method call, write `overflower::OverflowerStdAddKind::overflower_add_tag(&#[overflow(wrap)], #[overflow(wrap)])` instead
   = note: candidate #2 is defined in an impl of the trait `overflower::OverflowerAddKind` for the type `_`
   = help: to disambiguate the method call, write `overflower::OverflowerAddKind::overflower_add_tag(&#[overflow(wrap)], #[overflow(wrap)])` instead
```

This is the problem I initially feared and I didn't find in my earlier tests because I inadvertently removed the forwarding impls: I need to have an impl for `T` and `&T` for both my overriding traits and the original traits (well, we have them already). However, this means unless we have two levels of borrowing between those, we'll get some overlap. I have a hunch that I might be able to work around this by putting the Deref into the tag/kind mechanism, but I'm unsure how to implement it. Can you help me get this to work?

**Comment by dtolnay** [comment]
Is there a branch where I can reproduce the error you showed?

**Comment by llogiq** [comment]
[Yes there is](https://github.com/llogiq/overflower/tree/autoref)

**Comment by dtolnay** [comment]
I minimized your current implementation to:

```rust
use std::ops::Add;

pub trait OverflowerAdd<RHS = Self> {
    type Output;
    fn add_wrap(self, r: RHS) -> Self::Output;
}

pub struct StdAddTag;
pub struct OverflowerAddTag;

pub trait StdAddKind<R> {
    fn overflower_add_tag(&self, _: &R) -> StdAddTag {
        StdAddTag
    }
}

pub trait OverflowerAddKind<R> {
    fn overflower_add_tag(&self, _: &R) -> OverflowerAddTag {
        OverflowerAddTag
    }
}

impl<T, R> StdAddKind<R> for &T where T: Add<R> {}

impl<T, R> OverflowerAddKind<R> for T where T: OverflowerAdd<R> {}

impl StdAddTag {
    pub fn add_wrap<T: Add<R>, R>(self, t: T, r: R) -> T::Output {
        Add::add(t, r)
    }
}

impl OverflowerAddTag {
    pub fn add_wrap<T: OverflowerAdd<R>, R>(self, t: T, r: R) -> T::Output {
        OverflowerAdd::add_wrap(t, r)
    }
}

impl OverflowerAdd<u8> for u8 {
    type Output = u8;
    fn add_wrap(self, r: u8) -> Self::Output {
        self.wrapping_add(r)
    }
}

impl OverflowerAdd<u8> for &u8 {
    type Output = u8;
    fn add_wrap(self, r: u8) -> Self::Output {
        (*self).add_wrap(r)
    }
}

impl OverflowerAdd<&u8> for u8 {
    type Output = u8;
    fn add_wrap(self, r: &u8) -> Self::Output {
        self.add_wrap(*r)
    }
}

impl OverflowerAdd<&u8> for &u8 {
    type Output = u8;
    fn add_wrap(self, r: &u8) -> Self::Output {
        (*self).add_wrap(*r)
    }
}

fn main() {
    let (_x, _y) = (&255u8, 255u8);
    (&_x).overflower_add_tag(&_y).add_wrap(_x, _y);
}
```

```console
error[E0034]: multiple applicable items in scope
  --> src/main.rs:69:11
   |
69 |     (&_x).overflower_add_tag(&_y).add_wrap(_x, _y);
   |           ^^^^^^^^^^^^^^^^^^ multiple `overflower_add_tag` found
```

I would recommend implementing it instead as follows, which is a lot more like the way in the writeup:

```rust
use std::ops::Add;

pub trait OverflowerAdd<RHS = Self> {
    type Output;
    fn add_wrap(self, r: RHS) -> Self::Output;
}

pub struct StdAddTag;
pub struct OverflowerAddTag;

pub trait StdAddKind {
    fn overflower_add_tag(&self) -> StdAddTag {
        StdAddTag
    }
}

pub trait OverflowerAddKind {
    fn overflower_add_tag(&self) -> OverflowerAddTag {
        OverflowerAddTag
    }
}

impl<T, R> StdAddKind for &(&T, &R) where T: Add<R> {}

impl<T, R> OverflowerAddKind for (&T, &R) where T: OverflowerAdd<R> {}

impl StdAddTag {
    pub fn add_wrap<T: Add<R>, R>(self, t: T, r: R) -> T::Output {
        Add::add(t, r)
    }
}

impl OverflowerAddTag {
    pub fn add_wrap<T: OverflowerAdd<R>, R>(self, t: T, r: R) -> T::Output {
        OverflowerAdd::add_wrap(t, r)
    }
}

impl OverflowerAdd<u8> for u8 {
    type Output = u8;
    fn add_wrap(self, r: u8) -> Self::Output {
        self.wrapping_add(r)
    }
}

impl OverflowerAdd<u8> for &u8 {
    type Output = u8;
    fn add_wrap(self, r: u8) -> Self::Output {
        (*self).add_wrap(r)
    }
}

impl OverflowerAdd<&u8> for u8 {
    type Output = u8;
    fn add_wrap(self, r: &u8) -> Self::Output {
        self.add_wrap(*r)
    }
}

impl OverflowerAdd<&u8> for &u8 {
    type Output = u8;
    fn add_wrap(self, r: &u8) -> Self::Output {
        (*self).add_wrap(*r)
    }
}

fn main() {
    let (_x, _y) = (255u8, 255u8);
    (&(&_x, &_y)).overflower_add_tag().add_wrap(_x, _y);

    let (_x, _y) = (255u8, &255u8);
    (&(&_x, &_y)).overflower_add_tag().add_wrap(_x, _y);

    let (_x, _y) = (&255u8, 255u8);
    (&(&_x, &_y)).overflower_add_tag().add_wrap(_x, _y);

    let (_x, _y) = (&255u8, &255u8);
    (&(&_x, &_y)).overflower_add_tag().add_wrap(_x, _y);

    let (_x, _y) = (255usize, 255usize);
    (&(&_x, &_y)).overflower_add_tag().add_wrap(_x, _y);

    let (_x, _y) = (255usize, &255usize);
    (&(&_x, &_y)).overflower_add_tag().add_wrap(_x, _y);

    let (_x, _y) = (&255usize, 255usize);
    (&(&_x, &_y)).overflower_add_tag().add_wrap(_x, _y);

    let (_x, _y) = (&255usize, &255usize);
    (&(&_x, &_y)).overflower_add_tag().add_wrap(_x, _y);
}
```

**Comment by llogiq** [comment]
That did the trick. Thank you! I'll add some finishing touches, and then it'll be ready for version 1.0.0.
