### ISSUE TITLE
autoref specialization vs TypeId comparisons?

### ISSUE THREAD

**Issue by RReverser** [dtolnay/case-studies#12]
Not sure if issues is an appropriate place for such discussion, but after looking at #11 thought I'd share an alternative approach I've been using.

Autoref specialization case study mentions that it works only in macros but not in generic contexts like

```rust
pub fn demo<T: ???>(value: T) -> String {
    (&value).my_to_string()
}
```

However, one trick I've found to work well in such contexts is comparing `TypeId`s, e.g.:

```rust
pub fn format<T: 'static + ?Sized + std::fmt::Debug>(value: &T) -> String {
    use std::any::TypeId;

    if TypeId::of::<T>() == TypeId::of::<[u8]>() {
        format!("{:X?}", value)
    } else {
        format!("{:?}", value)
    }
}
```

It has own limitations, namely it works only for `'static` types due to restrictions on `TypeId`, but it's sometimes enough and works at least in some generic contexts.

Moreover, since the condition is comparing two constant values, optimiser is always able to remove it altogether in each monomorphised version of the function and instead unconditionally execute the correct branch, so this approach ends up being zero-cost, just like native specialization.

**Comment by dtolnay** [comment]
Neat! Thanks for sharing.
