### ISSUE TITLE
Recommend using match instead of let for autoref specialization

### ISSUE THREAD

**Issue by Koxiaet** [dtolnay/case-studies#15]
The problem with a macro definition such as:

```rust
macro_rules! anyhow {
    ($err:expr) => ({
        #[allow(unused_imports)]
        use $crate::{DisplayKind, StdErrorKind};
        let error = $err;
        (&error).anyhow_kind().new(error)
    });
}
```

Is that it won't work if `$err` relies on temporaries (e.g. it is `format_args!`). However, the following will work:

```rust
macro_rules! anyhow {
    ($err:expr) => ({
        #[allow(unused_imports)]
        use $crate::{DisplayKind, StdErrorKind};
        match $err {
            error => (&error).anyhow_kind().new(error),
        }
    });
}
```

as it's just one expression.

**Comment by dtolnay** [comment]
Good call, fixed. The reason this didn't come up in the real-world case in `anyhow` is that anyhow::Error requires a 'static argument for other reasons anyway.
